### ISSUE TITLE
Dry Code

### ISSUE THREAD

**Issue by jpbarela** [hockey2249/project_1#1]
These lines of code are repeated throughout the code. See if you can refactor the code to dry up the code.

https://github.com/hockey2249/project_1/blob/master/js/script.js#L25-L37

**Comment by hockey2249** [comment]
Hey JP,

I actually completed the dry method last night and created one master function to run all the duplicate code through. I will push my updated repository right now, let me know what you think.

Thanks again,
Kyle Gibbons
